theme: jekyll-theme-cayman
title: Mindful Meditation Timer
description: Find peace and mindfulness with our elegant meditation timer
show_downloads: false
google_analytics:
plugins:
  - jekyll-seo-tag